# Generated by Django 5.1.6 on 2025-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HRD", "HARD"), ("SFT", "SOFT")],
                default="SFT",
                max_length=100,
            ),
        ),
    ]
