# Generated by Django 5.1.6 on 2025-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_borrowing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="count_return_book",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
